import type { Question, QuestionCategory } from './types';

// Die Tupel sind bewusst als einfache, getrennte Datenquelle angelegt. Neue
// Fragen können hier ergänzt werden, ohne die Spiellogik zu verändern.
const questionData: ReadonlyArray<readonly [QuestionCategory, string]> = [
  ['Dating', 'Wer würde eher seinen Ex-Partner nachts anrufen?'],
  ['Dating', 'Wer würde eher beim ersten Date etwas extrem Peinliches erzählen?'],
  ['Dating', 'Wer würde eher schon vor dem ersten Date die ganze Familie der Person online suchen?'],
  ['Dating', 'Wer würde eher drei Dates gleichzeitig planen und die Namen verwechseln?'],
  ['Dating', 'Wer würde eher nach einem Date absichtlich zwei Tage mit der Antwort warten?'],
  ['Dating', 'Wer würde eher sich in jemanden verlieben, der völlig unerreichbar ist?'],
  ['Dating', 'Wer würde eher ein Date nur wegen eines schlechten Sternzeichens absagen?'],
  ['Dating', 'Wer würde eher beim Flirten einen Anmachspruch aus dem Internet benutzen?'],
  ['Dating', 'Wer würde eher den ersten Kuss komplett falsch einschätzen?'],
  ['Dating', 'Wer würde eher aus Versehen eine Dating-App-Nachricht an die falsche Person schicken?'],

  ['Beziehungen', 'Wer würde eher einen Jahrestag vergessen und so tun, als wäre eine Überraschung geplant?'],
  ['Beziehungen', 'Wer würde eher aus Eifersucht das Profil einer unbekannten Person durchforsten?'],
  ['Beziehungen', 'Wer würde eher in einer Diskussion „Ist mir egal“ sagen, obwohl es überhaupt nicht egal ist?'],
  ['Beziehungen', 'Wer würde eher heimlich eine Serie ohne den Partner weiterschauen?'],
  ['Beziehungen', 'Wer würde eher wegen einer winzigen Sache eine viel zu dramatische Nachricht schreiben?'],
  ['Beziehungen', 'Wer würde eher den Partner mit einem völlig unpassenden Kosenamen ansprechen?'],
  ['Beziehungen', 'Wer würde eher nach einem Streit zuerst ein Meme statt einer Entschuldigung schicken?'],
  ['Beziehungen', 'Wer würde eher den Schlüssel zur gemeinsamen Wohnung verlieren?'],
  ['Beziehungen', 'Wer würde eher beim Kennenlernen der Eltern in ein Fettnäpfchen treten?'],
  ['Beziehungen', 'Wer würde eher eine Beziehungspause vorschlagen und sie nach zwei Stunden bereuen?'],

  ['Freundschaft', 'Wer würde eher ein Geheimnis aus Versehen weitererzählen?'],
  ['Freundschaft', 'Wer würde eher eine Verabredung vergessen und erst durch eine Nachricht daran erinnert werden?'],
  ['Freundschaft', 'Wer würde eher beim Umzug helfen wollen und dann viel zu spät auftauchen?'],
  ['Freundschaft', 'Wer würde eher in der Gruppe einen Insider erklären und ihn dadurch ruinieren?'],
  ['Freundschaft', 'Wer würde eher eine peinliche Geschichte über Freunde vor deren Eltern erzählen?'],
  ['Freundschaft', 'Wer würde eher einen Gruppenchat stummschalten und danach nichts mehr verstehen?'],
  ['Freundschaft', 'Wer würde eher für einen Freund spontan durch halb Deutschland fahren?'],
  ['Freundschaft', 'Wer würde eher bei einem Spieleabend aus Ehrgeiz schlechte Stimmung machen?'],
  ['Freundschaft', 'Wer würde eher zehn Sprachnachrichten schicken, statt einmal anzurufen?'],
  ['Freundschaft', 'Wer würde eher ein ausgeliehenes Kleidungsstück jahrelang behalten?'],

  ['Party', 'Wer würde eher auf einer Party verschwinden, ohne sich zu verabschieden?'],
  ['Party', 'Wer würde eher als Erste oder Erster auf einer leeren Tanzfläche tanzen?'],
  ['Party', 'Wer würde eher die Musik übernehmen und nur die eigene Playlist spielen?'],
  ['Party', 'Wer würde eher auf einer fremden Party so tun, als würde man alle kennen?'],
  ['Party', 'Wer würde eher bei Karaoke voller Überzeugung den Text falsch singen?'],
  ['Party', 'Wer würde eher die Nachbarn zur Party einladen, damit sie sich nicht beschweren?'],
  ['Party', 'Wer würde eher auf dem Sofa einschlafen, während die Party noch läuft?'],
  ['Party', 'Wer würde eher beim Tanzen ein Glas umwerfen und unauffällig weitergehen?'],
  ['Party', 'Wer würde eher mit einer völlig fremden Person beste Freunde werden?'],
  ['Party', 'Wer würde eher am nächsten Morgen mit einem unbekannten Accessoire aufwachen?'],

  ['Alkohol', 'Wer würde eher nach einem Getränk behaupten, schon deutlich etwas zu merken?'],
  ['Alkohol', 'Wer würde eher beim Anstoßen das eigene Glas verschütten?'],
  ['Alkohol', 'Wer würde eher einen viel zu komplizierten Cocktail bestellen?'],
  ['Alkohol', 'Wer würde eher den eigenen Drink irgendwo abstellen und nicht wiederfinden?'],
  ['Alkohol', 'Wer würde eher plötzlich allen sagen, wie lieb man sie hat?'],
  ['Alkohol', 'Wer würde eher einen alkoholfreien Drink bestellen und ihn überzeugend als Cocktail verkaufen?'],
  ['Alkohol', 'Wer würde eher mitten am Abend einen sehr ernsten philosophischen Vortrag beginnen?'],
  ['Alkohol', 'Wer würde eher beim Öffnen einer Flasche eine kleine Katastrophe verursachen?'],
  ['Alkohol', 'Wer würde eher beim Trinkspiel die eigene Regel vergessen?'],
  ['Alkohol', 'Wer würde eher vernünftig Wasser für alle holen?'],

  ['Studium & Arbeit', 'Wer würde eher fünf Minuten vor Abgabe mit einer Aufgabe anfangen?'],
  ['Studium & Arbeit', 'Wer würde eher in einer Online-Vorlesung vergessen, das Mikrofon auszuschalten?'],
  ['Studium & Arbeit', 'Wer würde eher eine Präsentation komplett improvisieren und trotzdem überzeugen?'],
  ['Studium & Arbeit', 'Wer würde eher eine wichtige E-Mail mit „Hallo zusammen“ an nur eine Person schicken?'],
  ['Studium & Arbeit', 'Wer würde eher bei einer Prüfung genau das falsche Thema lernen?'],
  ['Studium & Arbeit', 'Wer würde eher im Meeting so tun, als hätte man alles verstanden?'],
  ['Studium & Arbeit', 'Wer würde eher den Namen einer Kollegin oder eines Kollegen monatelang nicht kennen?'],
  ['Studium & Arbeit', 'Wer würde eher versehentlich auf „Allen antworten“ klicken?'],
  ['Studium & Arbeit', 'Wer würde eher einen Termin verschlafen und eine kreative Ausrede erfinden?'],
  ['Studium & Arbeit', 'Wer würde eher mit einem Kaffeefleck auf dem Hemd in eine Präsentation gehen?'],

  ['Social Media', 'Wer würde eher ein altes Foto beim Stalken versehentlich liken?'],
  ['Social Media', 'Wer würde eher eine Story posten und sie nach zwei Minuten wieder löschen?'],
  ['Social Media', 'Wer würde eher länger an einer Bildunterschrift als am Bild selbst arbeiten?'],
  ['Social Media', 'Wer würde eher einen privaten Screenshot an genau die Person senden, um die es geht?'],
  ['Social Media', 'Wer würde eher eine peinliche Nachricht in den falschen Gruppenchat schicken?'],
  ['Social Media', 'Wer würde eher ein Essen fotografieren, bis es kalt ist?'],
  ['Social Media', 'Wer würde eher ein zweites Profil zum unauffälligen Beobachten haben?'],
  ['Social Media', 'Wer würde eher einen Trend mitmachen und ihn sofort bereuen?'],
  ['Social Media', 'Wer würde eher die eigene Bildschirmzeit deutlich zu niedrig schätzen?'],
  ['Social Media', 'Wer würde eher nachts um drei auf einen Kommentar von vor fünf Jahren antworten?'],

  ['Peinliche Momente', 'Wer würde eher einer Person zurückwinken, die jemand anderen gemeint hat?'],
  ['Peinliche Momente', 'Wer würde eher gegen eine Glastür laufen?'],
  ['Peinliche Momente', 'Wer würde eher im stillen Raum einen sehr lauten Magen haben?'],
  ['Peinliche Momente', 'Wer würde eher jemanden begeistert mit dem falschen Namen begrüßen?'],
  ['Peinliche Momente', 'Wer würde eher nach einem Witz als Einzige oder Einziger zu laut lachen?'],
  ['Peinliche Momente', 'Wer würde eher in der Öffentlichkeit stolpern und so tun, als wäre nichts passiert?'],
  ['Peinliche Momente', 'Wer würde eher mit offenem Reißverschluss durch den ganzen Tag laufen?'],
  ['Peinliche Momente', 'Wer würde eher an der Kasse merken, dass die Geldbörse zu Hause liegt?'],
  ['Peinliche Momente', 'Wer würde eher eine Sprachnachricht aufnehmen, während andere zuhören?'],
  ['Peinliche Momente', 'Wer würde eher in einen falschen Raum gehen und sich trotzdem erst einmal hinsetzen?'],

  ['Schlechte Entscheidungen', 'Wer würde eher spontan die Haare selbst schneiden?'],
  ['Schlechte Entscheidungen', 'Wer würde eher etwas Teures kaufen und es noch am selben Tag bereuen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher trotz leerem Akku ohne Ladekabel losfahren?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine Wette annehmen, ohne die Regeln richtig zu verstehen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen viel zu scharfen Snack probieren, um cool zu wirken?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine wichtige Entscheidung nach einem Persönlichkeitstest treffen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen Möbelaufbau ohne Anleitung beginnen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen Impulskauf mit „Das ist eine Investition“ rechtfertigen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher nachts noch eine Diskussion beginnen, die bis morgens dauert?'],
  ['Schlechte Entscheidungen', 'Wer würde eher „Das wird schon gutgehen“ sagen, kurz bevor es nicht gutgeht?'],

  ['Urlaub', 'Wer würde eher am Flughafen den Reisepass suchen müssen?'],
  ['Urlaub', 'Wer würde eher für drei Tage einen riesigen Koffer packen?'],
  ['Urlaub', 'Wer würde eher im Urlaub jeden Morgen einen genauen Zeitplan machen?'],
  ['Urlaub', 'Wer würde eher in die falsche Bahn oder den falschen Bus steigen?'],
  ['Urlaub', 'Wer würde eher einen Sonnenbrand bekommen, obwohl Sonnencreme dabei ist?'],
  ['Urlaub', 'Wer würde eher im Ausland selbstbewusst ein erfundenes Wort benutzen?'],
  ['Urlaub', 'Wer würde eher am ersten Urlaubstag das Zimmer oder Zelt chaotisch machen?'],
  ['Urlaub', 'Wer würde eher eine Sehenswürdigkeit nur für das perfekte Foto besuchen?'],
  ['Urlaub', 'Wer würde eher beim Packen etwas wirklich Wichtiges vergessen?'],
  ['Urlaub', 'Wer würde eher sich mit Einheimischen anfreunden und spontan den Plan ändern?'],

  ['Alltag', 'Wer würde eher das Handy suchen, während es in der eigenen Hand ist?'],
  ['Alltag', 'Wer würde eher dreimal den Wecker wegdrücken und dann in Rekordzeit fertig sein?'],
  ['Alltag', 'Wer würde eher eine Pflanze trotz bester Absichten vertrocknen lassen?'],
  ['Alltag', 'Wer würde eher die Wohnung aufräumen, um eine andere Aufgabe zu vermeiden?'],
  ['Alltag', 'Wer würde eher hungrig einkaufen und mit völlig unnötigen Snacks zurückkommen?'],
  ['Alltag', 'Wer würde eher einen ganzen Tag lang im Schlafanzug bleiben?'],
  ['Alltag', 'Wer würde eher beim Kochen gleichzeitig fünf Dinge anfangen?'],
  ['Alltag', 'Wer würde eher eine Verpackung öffnen und die Anleitung erst danach lesen?'],
  ['Alltag', 'Wer würde eher den Haustürschlüssel von innen stecken lassen?'],
  ['Alltag', 'Wer würde eher eine Serie an einem Wochenende komplett durchschauen?'],

  ['Geheimnisse', 'Wer würde eher ein überraschendes Doppelleben als Hobby haben?'],
  ['Geheimnisse', 'Wer würde eher heimlich mit sich selbst reden?'],
  ['Geheimnisse', 'Wer würde eher einen völlig unerwarteten Promi-Schwarm haben?'],
  ['Geheimnisse', 'Wer würde eher behaupten, einen Film gesehen zu haben, obwohl das nicht stimmt?'],
  ['Geheimnisse', 'Wer würde eher eine Notlüge erzählen und sich später darin verheddern?'],
  ['Geheimnisse', 'Wer würde eher heimlich die Nachrichten-Vorschau anderer lesen?'],
  ['Geheimnisse', 'Wer würde eher einen peinlichen Lieblingssong nur mit Kopfhörern hören?'],
  ['Geheimnisse', 'Wer würde eher ein Geschenk weiterverschenken und dabei erwischt werden?'],
  ['Geheimnisse', 'Wer würde eher einen Spitznamen hassen, aber nie etwas dagegen sagen?'],
  ['Geheimnisse', 'Wer würde eher eine große Neuigkeit am längsten für sich behalten können?'],
];

export const questions: readonly Question[] = questionData.map(([category, text], index) => ({
  id: `q${String(index + 1).padStart(3, '0')}`,
  category,
  text,
}));
