import type { Question, QuestionCategory } from './types';

// Die Tupel sind bewusst als einfache, getrennte Datenquelle angelegt. Neue
// Fragen können hier ergänzt werden, ohne die Spiellogik zu verändern.
const questionData: ReadonlyArray<readonly [QuestionCategory, string]> = [
  ['Dating', 'Wer würde eher seinen Ex-Partner nachts anrufen?'],
  ['Dating', 'Wer würde eher beim ersten Date etwas extrem Peinliches erzählen?'],
  ['Dating', 'Wer würde eher schon vor dem ersten Date die ganze Familie der Person online suchen?'],
  ['Dating', 'Wer würde eher drei Dates gleichzeitig planen und die Namen verwechseln?'],
  ['Dating', 'Wer würde eher nach einem Date absichtlich zwei Tage mit der Antwort warten?'],
  ['Dating', 'Wer würde eher sich in jemanden verlieben, der völlig unerreichbar ist?'],
  ['Dating', 'Wer würde eher ein Date nur wegen eines schlechten Sternzeichens absagen?'],
  ['Dating', 'Wer würde eher beim Flirten einen Anmachspruch aus dem Internet benutzen?'],
  ['Dating', 'Wer würde eher den ersten Kuss komplett falsch einschätzen?'],
  ['Dating', 'Wer würde eher aus Versehen eine Dating-App-Nachricht an die falsche Person schicken?'],

  ['Beziehungen', 'Wer würde eher einen Jahrestag vergessen und so tun, als wäre eine Überraschung geplant?'],
  ['Beziehungen', 'Wer würde eher aus Eifersucht das Profil einer unbekannten Person durchforsten?'],
  ['Beziehungen', 'Wer würde eher in einer Diskussion „Ist mir egal“ sagen, obwohl es überhaupt nicht egal ist?'],
  ['Beziehungen', 'Wer würde eher heimlich eine Serie ohne den Partner weiterschauen?'],
  ['Beziehungen', 'Wer würde eher wegen einer winzigen Sache eine viel zu dramatische Nachricht schreiben?'],
  ['Beziehungen', 'Wer würde eher den Partner mit einem völlig unpassenden Kosenamen ansprechen?'],
  ['Beziehungen', 'Wer würde eher nach einem Streit zuerst ein Meme statt einer Entschuldigung schicken?'],
  ['Beziehungen', 'Wer würde eher den Schlüssel zur gemeinsamen Wohnung verlieren?'],
  ['Beziehungen', 'Wer würde eher beim Kennenlernen der Eltern in ein Fettnäpfchen treten?'],
  ['Beziehungen', 'Wer würde eher eine Beziehungspause vorschlagen und sie nach zwei Stunden bereuen?'],

  ['Freundschaft', 'Wer würde eher ein Geheimnis aus Versehen weitererzählen?'],
  ['Freundschaft', 'Wer würde eher eine Verabredung vergessen und erst durch eine Nachricht daran erinnert werden?'],
  ['Freundschaft', 'Wer würde eher beim Umzug helfen wollen und dann viel zu spät auftauchen?'],
  ['Freundschaft', 'Wer würde eher in der Gruppe einen Insider erklären und ihn dadurch ruinieren?'],
  ['Freundschaft', 'Wer würde eher eine peinliche Geschichte über Freunde vor deren Eltern erzählen?'],
  ['Freundschaft', 'Wer würde eher einen Gruppenchat stummschalten und danach nichts mehr verstehen?'],
  ['Freundschaft', 'Wer würde eher für einen Freund spontan durch halb Deutschland fahren?'],
  ['Freundschaft', 'Wer würde eher bei einem Spieleabend aus Ehrgeiz schlechte Stimmung machen?'],
  ['Freundschaft', 'Wer würde eher zehn Sprachnachrichten schicken, statt einmal anzurufen?'],
  ['Freundschaft', 'Wer würde eher ein ausgeliehenes Kleidungsstück jahrelang behalten?'],

  ['Party', 'Wer würde eher auf einer Party verschwinden, ohne sich zu verabschieden?'],
  ['Party', 'Wer würde eher als Erste oder Erster auf einer leeren Tanzfläche tanzen?'],
  ['Party', 'Wer würde eher die Musik übernehmen und nur die eigene Playlist spielen?'],
  ['Party', 'Wer würde eher auf einer fremden Party so tun, als würde man alle kennen?'],
  ['Party', 'Wer würde eher bei Karaoke voller Überzeugung den Text falsch singen?'],
  ['Party', 'Wer würde eher die Nachbarn zur Party einladen, damit sie sich nicht beschweren?'],
  ['Party', 'Wer würde eher auf dem Sofa einschlafen, während die Party noch läuft?'],
  ['Party', 'Wer würde eher beim Tanzen ein Glas umwerfen und unauffällig weitergehen?'],
  ['Party', 'Wer würde eher mit einer völlig fremden Person beste Freunde werden?'],
  ['Party', 'Wer würde eher am nächsten Morgen mit einem unbekannten Accessoire aufwachen?'],

  ['Alkohol', 'Wer würde eher nach einem Getränk behaupten, schon deutlich etwas zu merken?'],
  ['Alkohol', 'Wer würde eher beim Anstoßen das eigene Glas verschütten?'],
  ['Alkohol', 'Wer würde eher einen viel zu komplizierten Cocktail bestellen?'],
  ['Alkohol', 'Wer würde eher den eigenen Drink irgendwo abstellen und nicht wiederfinden?'],
  ['Alkohol', 'Wer würde eher plötzlich allen sagen, wie lieb man sie hat?'],
  ['Alkohol', 'Wer würde eher einen alkoholfreien Drink bestellen und ihn überzeugend als Cocktail verkaufen?'],
  ['Alkohol', 'Wer würde eher mitten am Abend einen sehr ernsten philosophischen Vortrag beginnen?'],
  ['Alkohol', 'Wer würde eher beim Öffnen einer Flasche eine kleine Katastrophe verursachen?'],
  ['Alkohol', 'Wer würde eher beim Trinkspiel die eigene Regel vergessen?'],
  ['Alkohol', 'Wer würde eher vernünftig Wasser für alle holen?'],

  ['Studium & Arbeit', 'Wer würde eher fünf Minuten vor Abgabe mit einer Aufgabe anfangen?'],
  ['Studium & Arbeit', 'Wer würde eher in einer Online-Vorlesung vergessen, das Mikrofon auszuschalten?'],
  ['Studium & Arbeit', 'Wer würde eher eine Präsentation komplett improvisieren und trotzdem überzeugen?'],
  ['Studium & Arbeit', 'Wer würde eher eine wichtige E-Mail mit „Hallo zusammen“ an nur eine Person schicken?'],
  ['Studium & Arbeit', 'Wer würde eher bei einer Prüfung genau das falsche Thema lernen?'],
  ['Studium & Arbeit', 'Wer würde eher im Meeting so tun, als hätte man alles verstanden?'],
  ['Studium & Arbeit', 'Wer würde eher den Namen einer Kollegin oder eines Kollegen monatelang nicht kennen?'],
  ['Studium & Arbeit', 'Wer würde eher versehentlich auf „Allen antworten“ klicken?'],
  ['Studium & Arbeit', 'Wer würde eher einen Termin verschlafen und eine kreative Ausrede erfinden?'],
  ['Studium & Arbeit', 'Wer würde eher mit einem Kaffeefleck auf dem Hemd in eine Präsentation gehen?'],

  ['Social Media', 'Wer würde eher ein altes Foto beim Stalken versehentlich liken?'],
  ['Social Media', 'Wer würde eher eine Story posten und sie nach zwei Minuten wieder löschen?'],
  ['Social Media', 'Wer würde eher länger an einer Bildunterschrift als am Bild selbst arbeiten?'],
  ['Social Media', 'Wer würde eher einen privaten Screenshot an genau die Person senden, um die es geht?'],
  ['Social Media', 'Wer würde eher eine peinliche Nachricht in den falschen Gruppenchat schicken?'],
  ['Social Media', 'Wer würde eher ein Essen fotografieren, bis es kalt ist?'],
  ['Social Media', 'Wer würde eher ein zweites Profil zum unauffälligen Beobachten haben?'],
  ['Social Media', 'Wer würde eher einen Trend mitmachen und ihn sofort bereuen?'],
  ['Social Media', 'Wer würde eher die eigene Bildschirmzeit deutlich zu niedrig schätzen?'],
  ['Social Media', 'Wer würde eher nachts um drei auf einen Kommentar von vor fünf Jahren antworten?'],

  ['Peinliche Momente', 'Wer würde eher einer Person zurückwinken, die jemand anderen gemeint hat?'],
  ['Peinliche Momente', 'Wer würde eher gegen eine Glastür laufen?'],
  ['Peinliche Momente', 'Wer würde eher im stillen Raum einen sehr lauten Magen haben?'],
  ['Peinliche Momente', 'Wer würde eher jemanden begeistert mit dem falschen Namen begrüßen?'],
  ['Peinliche Momente', 'Wer würde eher nach einem Witz als Einzige oder Einziger zu laut lachen?'],
  ['Peinliche Momente', 'Wer würde eher in der Öffentlichkeit stolpern und so tun, als wäre nichts passiert?'],
  ['Peinliche Momente', 'Wer würde eher mit offenem Reißverschluss durch den ganzen Tag laufen?'],
  ['Peinliche Momente', 'Wer würde eher an der Kasse merken, dass die Geldbörse zu Hause liegt?'],
  ['Peinliche Momente', 'Wer würde eher eine Sprachnachricht aufnehmen, während andere zuhören?'],
  ['Peinliche Momente', 'Wer würde eher in einen falschen Raum gehen und sich trotzdem erst einmal hinsetzen?'],

  ['Schlechte Entscheidungen', 'Wer würde eher spontan die Haare selbst schneiden?'],
  ['Schlechte Entscheidungen', 'Wer würde eher etwas Teures kaufen und es noch am selben Tag bereuen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher trotz leerem Akku ohne Ladekabel losfahren?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine Wette annehmen, ohne die Regeln richtig zu verstehen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen viel zu scharfen Snack probieren, um cool zu wirken?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine wichtige Entscheidung nach einem Persönlichkeitstest treffen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen Möbelaufbau ohne Anleitung beginnen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen Impulskauf mit „Das ist eine Investition“ rechtfertigen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher nachts noch eine Diskussion beginnen, die bis morgens dauert?'],
  ['Schlechte Entscheidungen', 'Wer würde eher „Das wird schon gutgehen“ sagen, kurz bevor es nicht gutgeht?'],

  ['Urlaub', 'Wer würde eher am Flughafen den Reisepass suchen müssen?'],
  ['Urlaub', 'Wer würde eher für drei Tage einen riesigen Koffer packen?'],
  ['Urlaub', 'Wer würde eher im Urlaub jeden Morgen einen genauen Zeitplan machen?'],
  ['Urlaub', 'Wer würde eher in die falsche Bahn oder den falschen Bus steigen?'],
  ['Urlaub', 'Wer würde eher einen Sonnenbrand bekommen, obwohl Sonnencreme dabei ist?'],
  ['Urlaub', 'Wer würde eher im Ausland selbstbewusst ein erfundenes Wort benutzen?'],
  ['Urlaub', 'Wer würde eher am ersten Urlaubstag das Zimmer oder Zelt chaotisch machen?'],
  ['Urlaub', 'Wer würde eher eine Sehenswürdigkeit nur für das perfekte Foto besuchen?'],
  ['Urlaub', 'Wer würde eher beim Packen etwas wirklich Wichtiges vergessen?'],
  ['Urlaub', 'Wer würde eher sich mit Einheimischen anfreunden und spontan den Plan ändern?'],

  ['Alltag', 'Wer würde eher das Handy suchen, während es in der eigenen Hand ist?'],
  ['Alltag', 'Wer würde eher dreimal den Wecker wegdrücken und dann in Rekordzeit fertig sein?'],
  ['Alltag', 'Wer würde eher eine Pflanze trotz bester Absichten vertrocknen lassen?'],
  ['Alltag', 'Wer würde eher die Wohnung aufräumen, um eine andere Aufgabe zu vermeiden?'],
  ['Alltag', 'Wer würde eher hungrig einkaufen und mit völlig unnötigen Snacks zurückkommen?'],
  ['Alltag', 'Wer würde eher einen ganzen Tag lang im Schlafanzug bleiben?'],
  ['Alltag', 'Wer würde eher beim Kochen gleichzeitig fünf Dinge anfangen?'],
  ['Alltag', 'Wer würde eher eine Verpackung öffnen und die Anleitung erst danach lesen?'],
  ['Alltag', 'Wer würde eher den Haustürschlüssel von innen stecken lassen?'],
  ['Alltag', 'Wer würde eher eine Serie an einem Wochenende komplett durchschauen?'],

  ['Geheimnisse', 'Wer würde eher ein überraschendes Doppelleben als Hobby haben?'],
  ['Geheimnisse', 'Wer würde eher heimlich mit sich selbst reden?'],
  ['Geheimnisse', 'Wer würde eher einen völlig unerwarteten Promi-Schwarm haben?'],
  ['Geheimnisse', 'Wer würde eher behaupten, einen Film gesehen zu haben, obwohl das nicht stimmt?'],
  ['Geheimnisse', 'Wer würde eher eine Notlüge erzählen und sich später darin verheddern?'],
  ['Geheimnisse', 'Wer würde eher heimlich die Nachrichten-Vorschau anderer lesen?'],
  ['Geheimnisse', 'Wer würde eher einen peinlichen Lieblingssong nur mit Kopfhörern hören?'],
  ['Geheimnisse', 'Wer würde eher ein Geschenk weiterverschenken und dabei erwischt werden?'],
  ['Geheimnisse', 'Wer würde eher einen Spitznamen hassen, aber nie etwas dagegen sagen?'],
  ['Geheimnisse', 'Wer würde eher eine große Neuigkeit am längsten für sich behalten können?'],
];

const additionalQuestionData: ReadonlyArray<readonly [QuestionCategory, string]> = [
  // Dating · 17 zusätzliche Fragen
  ['Dating', 'Wer würde eher einen Kontakt schon vor dem ersten Date mit einem Herz-Emoji einspeichern?'],
  ['Dating', 'Wer würde eher viel zu früh am Treffpunkt sein und noch dreimal um den Block laufen?'],
  ['Dating', 'Wer würde eher sich allein wegen einer sympathischen Sprachnachricht verknallen?'],
  ['Dating', 'Wer würde eher jemanden ghosten und Wochen später versehentlich ein altes Foto liken?'],
  ['Dating', 'Wer würde eher vor einem Date einen Notfall-Anruf mit Freunden vereinbaren?'],
  ['Dating', 'Wer würde eher nach einem schlechten Date trotzdem sagen: „Das müssen wir wiederholen“?'],
  ['Dating', 'Wer würde eher nach einem richtig guten Chat gedanklich schon die Hochzeit planen?'],
  ['Dating', 'Wer würde eher beim Date viel zu lange über die eigene Ex-Beziehung reden?'],
  ['Dating', 'Wer würde eher beim zweiten Date immer noch nicht wissen, was die andere Person beruflich macht?'],
  ['Dating', 'Wer würde eher im falschen Restaurant auf das Date warten?'],
  ['Dating', 'Wer würde eher ein lockeres Gespräch vorher im Kopf komplett durchproben?'],
  ['Dating', 'Wer würde eher vor einem Date fünfmal das Outfit wechseln?'],
  ['Dating', 'Wer würde eher einen Anmachspruch von Freunden übernehmen und ihn komplett vermasseln?'],
  ['Dating', 'Wer würde eher beim Kennenlernen viel zu früh eine sehr persönliche Frage stellen?'],
  ['Dating', 'Wer würde eher einem Date hauptsächlich wegen des ausgewählten Restaurants zusagen?'],
  ['Dating', 'Wer würde eher reine Freundlichkeit sofort als Flirt interpretieren?'],
  ['Dating', 'Wer würde eher direkt nach dem Abschied schon die nächste Nachricht schicken?'],

  // Beziehungen · 17 zusätzliche Fragen
  ['Beziehungen', 'Wer würde eher nachts die komplette Bettdecke an sich ziehen?'],
  ['Beziehungen', 'Wer würde eher eine perfekte Antwort auf einen Streit erst unter der Dusche finden?'],
  ['Beziehungen', 'Wer würde eher alte Chats lesen, nur um sich wieder an den Anfang der Beziehung zu erinnern?'],
  ['Beziehungen', 'Wer würde eher spontan ein gemeinsames Haustier vorschlagen?'],
  ['Beziehungen', 'Wer würde eher aus einer kleinen Meinungsverschiedenheit einen Grundsatzstreit machen?'],
  ['Beziehungen', 'Wer würde eher genau die eine Sache beim Einkaufen vergessen, um die gebeten wurde?'],
  ['Beziehungen', 'Wer würde eher den Standort teilen, obwohl niemand danach gefragt hat?'],
  ['Beziehungen', 'Wer würde eher eine passiv-aggressive Nachricht schreiben und sie dann doch löschen?'],
  ['Beziehungen', 'Wer würde eher bei dem Film einschlafen, den man selbst unbedingt sehen wollte?'],
  ['Beziehungen', 'Wer würde eher sofort ein gemeinsames Profilbild einstellen?'],
  ['Beziehungen', 'Wer würde eher passende Partner-Outfits kaufen wollen?'],
  ['Beziehungen', 'Wer würde eher bei einem neuen Streit plötzlich ein drei Jahre altes Thema hervorholen?'],
  ['Beziehungen', 'Wer würde eher nach jedem kleinen Konflikt Beziehungstipps googeln?'],
  ['Beziehungen', 'Wer würde eher einen geheimen Snackvorrat vor dem Partner verstecken?'],
  ['Beziehungen', 'Wer würde eher beim Familienessen eine wichtige Person mit dem falschen Namen ansprechen?'],
  ['Beziehungen', 'Wer würde eher gemeinsame Pläne absagen wollen, um zusammen auf dem Sofa zu bleiben?'],
  ['Beziehungen', 'Wer würde eher den gemeinsamen Urlaub mit einer detaillierten Tabelle planen?'],

  // Freundschaft · 17 zusätzliche Fragen
  ['Freundschaft', 'Wer würde eher nach Jahren ein großes Wiedersehen der alten Gruppe organisieren?'],
  ['Freundschaft', 'Wer würde eher tagelang nicht im Gruppenchat antworten und trotzdem plötzlich beim Treffen auftauchen?'],
  ['Freundschaft', 'Wer würde eher geliehenes Geld vergessen, bis die Banking-App daran erinnert?'],
  ['Freundschaft', 'Wer würde eher unangekündigt mit den Lieblingssnacks vor der Tür stehen?'],
  ['Freundschaft', 'Wer würde eher von allen als Notfallkontakt eingetragen werden?'],
  ['Freundschaft', 'Wer würde eher Freunde ständig aufziehen, sie aber vor anderen sofort verteidigen?'],
  ['Freundschaft', 'Wer würde eher einen gemeinsamen Roadtrip vorschlagen und danach nichts mehr planen?'],
  ['Freundschaft', 'Wer würde eher bei jedem Treffen zweihundert Gruppenfotos machen?'],
  ['Freundschaft', 'Wer würde eher alle Geburtstage ohne Erinnerung kennen?'],
  ['Freundschaft', 'Wer würde eher in einer neuen Runde sofort ein peinliches altes Foto zeigen?'],
  ['Freundschaft', 'Wer würde eher aus einem kurzen Telefonat ein dreistündiges Gespräch machen?'],
  ['Freundschaft', 'Wer würde eher einen Freund für mehrere Wochen auf dem eigenen Sofa wohnen lassen?'],
  ['Freundschaft', 'Wer würde eher „Bin unterwegs“ schreiben, obwohl man noch unter der Dusche steht?'],
  ['Freundschaft', 'Wer würde eher aus einer harmlosen Bemerkung eine komplette Detektivgeschichte machen?'],
  ['Freundschaft', 'Wer würde eher eine ruhige Person auf einer Party sofort in die Gruppe aufnehmen?'],
  ['Freundschaft', 'Wer würde eher die ganze Gruppe zu einem spontanen Tattoo überreden?'],
  ['Freundschaft', 'Wer würde eher ein wichtiges Geheimnis auch unter größtem Druck für sich behalten?'],

  // Party · 17 zusätzliche Fragen
  ['Party', 'Wer würde eher am Ende der Nacht die eigene Jacke nicht mehr finden?'],
  ['Party', 'Wer würde eher mit dem DJ über den nächsten Song diskutieren?'],
  ['Party', 'Wer würde eher spontan eine Polonaise durch die ganze Wohnung starten?'],
  ['Party', 'Wer würde eher den gesamten Abend in der Küche verbringen und dort die besten Gespräche führen?'],
  ['Party', 'Wer würde eher als letzte Person kommen und bis zum Schluss bleiben?'],
  ['Party', 'Wer würde eher Snacks mitbringen und sie dann im Auto vergessen?'],
  ['Party', 'Wer würde eher nach zehn Minuten schon das Barpersonal beim Namen kennen?'],
  ['Party', 'Wer würde eher plötzlich auf einem Stuhl tanzen?'],
  ['Party', 'Wer würde eher um zwei Uhr morgens noch eine Afterparty organisieren?'],
  ['Party', 'Wer würde eher bei der Ankunft erst einmal an der falschen Wohnung klingeln?'],
  ['Party', 'Wer würde eher völlig overdressed zu einer entspannten Gartenparty erscheinen?'],
  ['Party', 'Wer würde eher ungefragt ein neues Gruppenspiel anfangen?'],
  ['Party', 'Wer würde eher irgendwann barfuß auf der Tanzfläche stehen?'],
  ['Party', 'Wer würde eher ein Gruppenfoto machen, auf dem die Hälfte der Gruppe fehlt?'],
  ['Party', 'Wer würde eher mit einem einzigen Song die ganze Tanzfläche retten?'],
  ['Party', 'Wer würde eher für einen Musikwunsch charmant mit dem DJ flirten?'],
  ['Party', 'Wer würde eher am nächsten Morgen freiwillig beim Aufräumen helfen?'],

  // Alkohol · 17 zusätzliche Fragen
  ['Alkohol', 'Wer würde eher den ganzen Abend beim exakt gleichen Getränk bleiben?'],
  ['Alkohol', 'Wer würde eher zu viele verschiedene Getränke durcheinanderprobieren?'],
  ['Alkohol', 'Wer würde eher immer einen Flaschenöffner dabeihaben?'],
  ['Alkohol', 'Wer würde eher das eigene Glas mit dem einer anderen Person verwechseln?'],
  ['Alkohol', 'Wer würde eher beim Anstoßen hektisch versuchen, wirklich allen in die Augen zu schauen?'],
  ['Alkohol', 'Wer würde eher einer fremden Person plötzlich die gesamte Lebensgeschichte erzählen?'],
  ['Alkohol', 'Wer würde eher eine Runde ankündigen und selbst heimlich bei Wasser bleiben?'],
  ['Alkohol', 'Wer würde eher beim Weiterreichen eines Getränks die Hälfte verschütten?'],
  ['Alkohol', 'Wer würde eher einen eigenen Cocktail erfinden, der niemandem schmeckt?'],
  ['Alkohol', 'Wer würde eher nachts einen unstillbaren Hunger auf Fast Food bekommen?'],
  ['Alkohol', 'Wer würde eher am nächsten Morgen noch jedes Detail des Abends erzählen können?'],
  ['Alkohol', 'Wer würde eher schon nach kurzer Zeit nicht mehr wissen, das wievielte Getränk es ist?'],
  ['Alkohol', 'Wer würde eher beim Beerpong plötzlich extrem ehrgeizig werden?'],
  ['Alkohol', 'Wer würde eher dreimal „Nur noch eins“ sagen?'],
  ['Alkohol', 'Wer würde eher für alle ein Taxi organisieren und sicherstellen, dass jeder heimkommt?'],
  ['Alkohol', 'Wer würde eher nach einem guten Cocktail direkt nach dem Rezept fragen?'],
  ['Alkohol', 'Wer würde eher freiwillig früh auf Wasser umsteigen?'],

  // Studium & Arbeit · 17 zusätzliche Fragen
  ['Studium & Arbeit', 'Wer würde eher eine Hausarbeit in einer einzigen langen Nacht fertigschreiben?'],
  ['Studium & Arbeit', 'Wer würde eher im Seminar eine Frage stellen, obwohl alle schon gehen wollen?'],
  ['Studium & Arbeit', 'Wer würde eher für eine Gruppenarbeit am Ende fast alles selbst machen?'],
  ['Studium & Arbeit', 'Wer würde eher während eines Meetings unbemerkt online einkaufen?'],
  ['Studium & Arbeit', 'Wer würde eher eine Abgabefrist im falschen Kalender eintragen?'],
  ['Studium & Arbeit', 'Wer würde eher mit einer viel zu aufwendigen Präsentation alle überraschen?'],
  ['Studium & Arbeit', 'Wer würde eher den Laptop aufklappen und sofort ein Update installieren müssen?'],
  ['Studium & Arbeit', 'Wer würde eher in einer Vorlesung einschlafen und beim Aufwachen so tun, als wäre nichts gewesen?'],
  ['Studium & Arbeit', 'Wer würde eher dem Chef aus Versehen ein Meme schicken?'],
  ['Studium & Arbeit', 'Wer würde eher bei einer wichtigen Aufgabe erst einmal den Schreibtisch perfekt aufräumen?'],
  ['Studium & Arbeit', 'Wer würde eher im Bewerbungsgespräch eine unerwartet ehrliche Antwort geben?'],
  ['Studium & Arbeit', 'Wer würde eher eine Excel-Tabelle für etwas erstellen, das man auch auf einen Zettel schreiben könnte?'],
  ['Studium & Arbeit', 'Wer würde eher in der Mittagspause eine Diskussion über Arbeit anfangen?'],
  ['Studium & Arbeit', 'Wer würde eher eine Nachricht mit Tippfehler genau an die Geschäftsführung senden?'],
  ['Studium & Arbeit', 'Wer würde eher einen ganzen Lerntag planen und am Ende nur die Überschriften markieren?'],
  ['Studium & Arbeit', 'Wer würde eher im Homeoffice den ganzen Tag eine Jogginghose tragen?'],
  ['Studium & Arbeit', 'Wer würde eher freiwillig die Moderation einer Präsentation übernehmen?'],

  // Social Media · 17 zusätzliche Fragen
  ['Social Media', 'Wer würde eher eine Story nur für eine ganz bestimmte Person posten?'],
  ['Social Media', 'Wer würde eher einen Beitrag löschen, weil er nach zehn Minuten zu wenige Likes hat?'],
  ['Social Media', 'Wer würde eher einen Urlaub fast nur durch die Handykamera erleben?'],
  ['Social Media', 'Wer würde eher einen Filter benutzen und behaupten, das Licht sei einfach gut gewesen?'],
  ['Social Media', 'Wer würde eher aus Versehen live gehen?'],
  ['Social Media', 'Wer würde eher nachts stundenlang durch Kurzvideos scrollen?'],
  ['Social Media', 'Wer würde eher einen Account für das eigene Haustier erstellen?'],
  ['Social Media', 'Wer würde eher eine Nachricht lesen und absichtlich erst Stunden später antworten?'],
  ['Social Media', 'Wer würde eher eine komplizierte Fotopose üben, die spontan aussehen soll?'],
  ['Social Media', 'Wer würde eher in einer Diskussion mit einem fremden Account völlig die Zeit vergessen?'],
  ['Social Media', 'Wer würde eher jedes Restaurant vor dem Besuch online überprüfen?'],
  ['Social Media', 'Wer würde eher das eigene Profilbild jede Woche ändern?'],
  ['Social Media', 'Wer würde eher eine peinliche Story bis zum Ende online lassen?'],
  ['Social Media', 'Wer würde eher einen ganzen Chatverlauf analysieren und Freunden Screenshots schicken?'],
  ['Social Media', 'Wer würde eher ein virales Rezept ausprobieren, obwohl es offensichtlich nicht funktioniert?'],
  ['Social Media', 'Wer würde eher einen Hashtag komplett falsch verstehen?'],
  ['Social Media', 'Wer würde eher das Handy entsperren und sofort vergessen, welche App geöffnet werden sollte?'],

  // Peinliche Momente · 17 zusätzliche Fragen
  ['Peinliche Momente', 'Wer würde eher nach „Guten Appetit“ reflexartig „Danke, gleichfalls“ antworten?'],
  ['Peinliche Momente', 'Wer würde eher in einen Raum platzen und sofort merken, dass gerade etwas Ernstes besprochen wird?'],
  ['Peinliche Momente', 'Wer würde eher einen Witz erzählen und die Pointe vergessen?'],
  ['Peinliche Momente', 'Wer würde eher beim Aussteigen merken, dass man im falschen Zug sitzt?'],
  ['Peinliche Momente', 'Wer würde eher laut mitsingen und erst spät bemerken, dass die Kopfhörer gar nicht verbunden sind?'],
  ['Peinliche Momente', 'Wer würde eher an einer Tür ziehen, auf der deutlich „Drücken“ steht?'],
  ['Peinliche Momente', 'Wer würde eher eine Person umarmen wollen, die nur die Hand geben wollte?'],
  ['Peinliche Momente', 'Wer würde eher in einer stillen Runde versehentlich ein Video mit voller Lautstärke starten?'],
  ['Peinliche Momente', 'Wer würde eher beim Bezahlen die falsche PIN eingeben und sie danach laut aufsagen?'],
  ['Peinliche Momente', 'Wer würde eher beim Smalltalk eine Frage stellen, deren Antwort gerade schon genannt wurde?'],
  ['Peinliche Momente', 'Wer würde eher im falschen Auto versuchen, die Tür aufzuschließen?'],
  ['Peinliche Momente', 'Wer würde eher beim Fotografieren rückwärts gegen etwas laufen?'],
  ['Peinliche Momente', 'Wer würde eher einen fremden Hund begeistert mit dem falschen Namen rufen?'],
  ['Peinliche Momente', 'Wer würde eher beim Vorstellen den eigenen Namen falsch aussprechen?'],
  ['Peinliche Momente', 'Wer würde eher glauben, eine Frage sei an jemand anderen gerichtet, und viel zu spät antworten?'],
  ['Peinliche Momente', 'Wer würde eher eine vertrauliche Nachricht auf einem geteilten Bildschirm öffnen?'],
  ['Peinliche Momente', 'Wer würde eher beim stillen Händeschütteln ein viel zu lautes Geräusch verursachen?'],

  // Schlechte Entscheidungen · 16 zusätzliche Fragen
  ['Schlechte Entscheidungen', 'Wer würde eher kurz vor einer Reise noch eine völlig neue Frisur ausprobieren?'],
  ['Schlechte Entscheidungen', 'Wer würde eher ohne Wetterbericht in Sandalen zu einer Wanderung starten?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine Abkürzung nehmen und dadurch doppelt so lange brauchen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher ein Möbelstück kaufen, ohne vorher die Maße zu prüfen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher auf „Später erinnern“ klicken, bis ein wichtiges Update alles blockiert?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine Challenge annehmen, nur weil jemand „Du traust dich nicht“ sagt?'],
  ['Schlechte Entscheidungen', 'Wer würde eher mit fast leerem Tank noch an drei Tankstellen vorbeifahren?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen weißen Pullover zu einem Essen mit Tomatensoße tragen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine komplizierte Reparatur nach einem einzigen Kurzvideo beginnen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen Flug mit extrem kurzer Umsteigezeit buchen, um Geld zu sparen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher beim Onlinekauf die Bewertungen erst nach der Bestellung lesen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine große Packung eines Snacks kaufen, den man noch nie probiert hat?'],
  ['Schlechte Entscheidungen', 'Wer würde eher trotz früher Verpflichtung „nur kurz“ mit auf eine Party kommen?'],
  ['Schlechte Entscheidungen', 'Wer würde eher eine wichtige Datei bearbeiten, ohne vorher eine Kopie zu speichern?'],
  ['Schlechte Entscheidungen', 'Wer würde eher beim Kochen spontan fünf Rezepte miteinander kombinieren?'],
  ['Schlechte Entscheidungen', 'Wer würde eher einen Streit per Textnachricht lösen wollen?'],

  // Urlaub · 16 zusätzliche Fragen
  ['Urlaub', 'Wer würde eher erst am Flughafen prüfen, ob der Reisepass noch gültig ist?'],
  ['Urlaub', 'Wer würde eher im Hotel sofort das beste Restaurant der Stadt recherchieren?'],
  ['Urlaub', 'Wer würde eher einen Tagesausflug komplett spontan ohne Plan beginnen?'],
  ['Urlaub', 'Wer würde eher beim Camping als Erstes den Dosenöffner vergessen?'],
  ['Urlaub', 'Wer würde eher im Urlaub jeden Sonnenuntergang fotografieren?'],
  ['Urlaub', 'Wer würde eher eine fremde Sprache mit Händen, Füßen und sehr viel Selbstvertrauen sprechen?'],
  ['Urlaub', 'Wer würde eher am Strand einschlafen und mit einem seltsamen Abdruck aufwachen?'],
  ['Urlaub', 'Wer würde eher im Souvenirladen viel zu viel Geld ausgeben?'],
  ['Urlaub', 'Wer würde eher auf einer Reise sofort lokale Spezialitäten probieren?'],
  ['Urlaub', 'Wer würde eher die gesamte Gruppe morgens viel zu früh wecken?'],
  ['Urlaub', 'Wer würde eher trotz Navigation dreimal am gleichen Platz vorbeilaufen?'],
  ['Urlaub', 'Wer würde eher im Urlaub jemanden kennenlernen und danach jahrelang Kontakt halten?'],
  ['Urlaub', 'Wer würde eher das Rückflugdatum einen Tag zu spät im Kopf haben?'],
  ['Urlaub', 'Wer würde eher mehr Ladegeräte als Kleidungsstücke einpacken?'],
  ['Urlaub', 'Wer würde eher bei einer Stadtführung ständig eigene Zusatzinformationen liefern?'],
  ['Urlaub', 'Wer würde eher eine Reise wegen eines einzigen perfekten Fotos buchen?'],

  // Alltag · 16 zusätzliche Fragen
  ['Alltag', 'Wer würde eher den Kaffee machen und ihn dann in der Küche stehen lassen?'],
  ['Alltag', 'Wer würde eher eine Einkaufsliste schreiben und sie zu Hause vergessen?'],
  ['Alltag', 'Wer würde eher den ganzen Tag mit zwei unterschiedlichen Socken herumlaufen?'],
  ['Alltag', 'Wer würde eher eine Erinnerung stellen und trotzdem nicht wissen, woran sie erinnern sollte?'],
  ['Alltag', 'Wer würde eher beim Putzen plötzlich alte Fotos anschauen und alles andere vergessen?'],
  ['Alltag', 'Wer würde eher zehn offene Tabs behalten, weil alle noch wichtig sein könnten?'],
  ['Alltag', 'Wer würde eher eine Mahlzeit bestellen, obwohl der Kühlschrank voll ist?'],
  ['Alltag', 'Wer würde eher beim Telefonieren ziellos durch die ganze Wohnung laufen?'],
  ['Alltag', 'Wer würde eher einen neuen Gegenstand kaufen, weil der alte nur nicht gefunden wird?'],
  ['Alltag', 'Wer würde eher jeden Deckel aufbewahren, aber nie die passende Dose finden?'],
  ['Alltag', 'Wer würde eher den Wecker für einen freien Tag versehentlich eingeschaltet lassen?'],
  ['Alltag', 'Wer würde eher beim Kochen schon satt werden, weil ständig probiert wird?'],
  ['Alltag', 'Wer würde eher eine Nachricht anfangen und erst zwei Tage später abschicken?'],
  ['Alltag', 'Wer würde eher mit nassen Haaren aus dem Haus gehen und es sofort bereuen?'],
  ['Alltag', 'Wer würde eher einen Karton monatelang aufbewahren, weil man ihn vielleicht noch braucht?'],
  ['Alltag', 'Wer würde eher mitten im Aufräumen das Zimmer komplett umgestalten?'],

  // Geheimnisse · 16 zusätzliche Fragen
  ['Geheimnisse', 'Wer würde eher heimlich eine Liste mit möglichen Namen für zukünftige Haustiere führen?'],
  ['Geheimnisse', 'Wer würde eher eine Serie lieben, über die man sich öffentlich immer lustig macht?'],
  ['Geheimnisse', 'Wer würde eher im Spiegel ganze Gespräche üben?'],
  ['Geheimnisse', 'Wer würde eher noch einen alten Glücksbringer aus der Kindheit besitzen?'],
  ['Geheimnisse', 'Wer würde eher heimlich die eigenen alten Social-Media-Beiträge durchsehen?'],
  ['Geheimnisse', 'Wer würde eher ein Talent haben, von dem die Gruppe überhaupt nichts weiß?'],
  ['Geheimnisse', 'Wer würde eher einen erfundenen Namen für Essensbestellungen benutzen?'],
  ['Geheimnisse', 'Wer würde eher heimlich Bewertungen über Orte schreiben?'],
  ['Geheimnisse', 'Wer würde eher eine Schublade voller völlig unnötiger Erinnerungsstücke haben?'],
  ['Geheimnisse', 'Wer würde eher vor anderen cool wirken und allein bei Filmen sofort weinen?'],
  ['Geheimnisse', 'Wer würde eher einen zweiten Wecker stellen und den ersten nur zum Genießen des Weiterschlafens nutzen?'],
  ['Geheimnisse', 'Wer würde eher sich selbst Nachrichten schicken, um nichts zu vergessen?'],
  ['Geheimnisse', 'Wer würde eher einen heimlichen Lieblingsplatz haben, den niemand kennt?'],
  ['Geheimnisse', 'Wer würde eher ein Geschenk schon vor dem Geburtstag erraten und nichts sagen?'],
  ['Geheimnisse', 'Wer würde eher eine völlig unerwartete Sammlung zu Hause haben?'],
  ['Geheimnisse', 'Wer würde eher seit Jahren denselben geheimen Wunsch auf einer Liste stehen haben?'],
];

export const questions: readonly Question[] = [...questionData, ...additionalQuestionData].map(([category, text], index) => ({
  id: `q${String(index + 1).padStart(3, '0')}`,
  category,
  text,
}));
